### ISSUE TITLE
multi tenant

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#102]
is it possible to create a multi tenant application using this revenj? i want to use single db for each user
Thanks

**Comment by zapov** [comment]
You mean you want to use a different DB for each tenant?
The way to go about that is to have Container instance per each tenant.
Then just pass along request using the appropriate container instance and it should work as expected.

**Comment by araneta** [comment]
i'm not sure how to do this. because you are using service locator to instantiate Container

```
 Container ctx = locator.resolve(Container.class);
      this.connection = DriverManager.getConnection(jdbcUrl);
      connection.setAutoCommit(true);
      ctx.registerInstance(connection);
```

**Comment by zapov** [comment]
Container.createScope() should give you a scope where you can register connection per user

Then when the requests comes, resolve scope for that user and run queries in that scope.
Something along the lines of

    Map<Long, Container> scopes = ...
    Container getUserContainer(user: Long) {
      Container ctx = scopes.get(user);
      if (ctx == null) { 
        Container root = locator.resolve(Container.class); 
        Connection connection = ... //create connection for that user
        ctx = root.createScope();
        scope.registerInstance(connection);
        scopes.put(user, ctx);
      }
      return ctx
    }

**Comment by zapov** [comment]
It doesnt work since Revenj doesn't register all implementations when you do container.registerInstance

Maybe it should.

Until then you can get this working by registering

    ctx.registerAs(c, Connection.class);

instead of

    ctx.registerInstance(c);

But I suggest changing it to use separate root containers instead of nested scopes.
Thats seems much more safe for multiple reasons:

  * there will be no URL sharing withing the container (currently you have one connection URL at the top container and different URLs at nested containers)
  * you can use DataSource than as expected. This setup registers a single connection per scope, but it's more robust to take connection of DataSource

so instead of setting up nested scope, instead do something like

    ctx = Boot.configure(tenant.get().getDbConfig(), tenantProps);

**Comment by araneta** [comment]
thanks. i have updated the code to this:

```
public Container getUserContainer(UUID userId) {
        Container ctx = scopes.get(userId);
        if (ctx == null) {

            //get db url of this.tenants.
            final Optional<Tenant> tenant = tenants.find(userId, connection);
            if(tenant.isPresent()){
                try {
                    String url = tenant.get().getDbConfig();
                    System.out.print(url);

                    Connection c = DriverManager.getConnection(url);
					ServiceLocator locatorx;
					Properties props = new Properties();
					props.setProperty("revenj.notifications.status", "disabled");
					locatorx = Boot.configure(url, props);
					ctx = locatorx.resolve(Container.class);
					ctx.registerAs(c, Connection.class);
                    scopes.put(userId, ctx);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }else{
                return null;
            }

        }
        return ctx;
    }

```
is it correct? i tried it and its working. and when should we remove container from scopes ?
right now i have 2 dsl files. tenants.dsl and university.dsl. is it possible to implement tenants.dsl to database: ujianku and the other dsl university.dsl to database: db1. right all database have the same schema / structure

**Comment by zapov** [comment]
instead of this:

            Connection c = DriverManager.getConnection(url);
					ServiceLocator locatorx;
					Properties props = new Properties();
					props.setProperty("revenj.notifications.status", "disabled");
					locatorx = Boot.configure(url, props);
					ctx = locatorx.resolve(Container.class);
					ctx.registerAs(c, Connection.class);

just this

					ctx = Boot.configure(url, new Properties());

Yes, its possible, but it would require several maven projects to setup via this tools

**Comment by araneta** [comment]
i can't compile this ctx = Boot.configure(url, new Properties());
[111,61] incompatible types: org.revenj.patterns.ServiceLocator cannot be converted to org.revenj.extensibility.Container

**Comment by zapov** [comment]
Either cast it or change the signature of scopes map.
You don't need to remove them since you are not opening up a connection that way

**Comment by araneta** [comment]
thanks a lot for your help
