### ISSUE TITLE
SQL concept but with database functions

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#104]
I can define SQL in the DSL model using the [SQL concept](https://github.com/ngs-doo/revenj/blob/master/tutorials/revenj-tutorial-raw-sql.md)

It works for `select`'s from `tables` and `views`, is there any way to use it for a `select` from a database `function`?
ie

```
SQL MyPostgresFunction <#
  SELECT col1, col2, col3
  FROM MyPostgresFunction(:param1, :param2)
#> {
  int col1;
  int col2;
  string col3;
}
```

**Comment by zapov** [comment]
Not like that. The best workaround is to use just the converter part for mapping boilerplate... and call the sql via ADO.NET

    SQL MyPostgresFunction <#  SELECT * FROM MyPostgresFunction(null, null) #> {
      int col1;
      int col2;
      string col3;
    }

**Comment by Kobus-Smit** [comment]
Ok thanks
