### ISSUE TITLE
Client lib does not compile DSL with mixin

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#108]
Client library does not compile for this dsl: (Compiler: 2.1.6732.31277)
```
module Test {

mixin MyMixin {
	string ABC;
}

root MyRoot { 
	has mixin MyMixin;
}

}
```

```
Error during compilation:
No overload for method 'Clone' takes 1 arguments
```

![image](https://user-images.githubusercontent.com/11263864/41495276-b3865b62-7166-11e8-8933-9d2bdfca0987.png)

Test project: https://github.com/Kobus-Smit/revenj-examples/tree/master/MixinCompileError

**Comment by zapov** [comment]
Tnx for the bug report.
Fixed in the latest compiler version

**Comment by Kobus-Smit** [comment]
Thanks @zapov
