### ISSUE TITLE
using revenj with vertx

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#109]
Is it possible to use this revenj inside a verticle (vertx)? please give me some directions, Thanks

**Comment by zapov** [comment]
As a library you should be able to use it from any other framework.

But Java version doesn't really fit well with Vertx which prefers the async API, while the Revenj Java API is blocking. Thats not really a blocker, just a bit unnatural for Vertx.

I don't have any examples, but it should boil down to the same Container initialization as in any other framework.

**Comment by araneta** [comment]
yes youre right Vertx suggests to use async api
