### ISSUE TITLE
Implement IEditableObject

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#112]
Hi @zapov 

Can the Revenj compiler generate client classes that implement [IEditableObject](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.ieditableobject?redirectedfrom=MSDN&view=netframework-4.7.2)?

This would be very useful to enable rollback functionality in data grid components, for example: [[1]](https://www.devexpress.com/Support/Center/Question/Details/B155096/if-the-exceptionmode-ignore-is-applied-the-cell-value-isn-t-reseted-to-previous) [[2]](https://www.devexpress.com/Support/Center/Question/Details/T556533/gridview-roll-back-changes) [[3]](https://documentation.devexpress.com/WindowsForms/DevExpress.XtraGrid.Views.Base.ColumnView.CancelUpdateCurrentRow.method)

Would be much appreciated.

**Comment by zapov** [comment]
C# server code has a notion of track changes, which keeps around original version of the object. I guess that could be used to implement such a feature in a generic manner.

But I guess you need this on a C# client target? I don't think it support track changes in such a manner. But it makes sense to have that feature in client target also.

**Comment by Kobus-Smit** [comment]
C# client correct.

I'm currently inheriting from the client class and implementing
IEditableObject myself (otherwise I can't use the nice XtraGrid component)
Simply using backup variables as in the DevExpress example (not as in the
MSDN link), and it works but it's repetitive plumbing and casting etc. :-)

**Comment by zapov** [comment]
What you can do is define a mixin with some custom code. You can add custom code via the mapping of an implementation feature, eg:

    module test {
      mixin EditableObject {
        implements c# 'System.ComponentModel.IEditableObject' {
          <# 
            dynamic __original;
            void System.ComponentModel.IEditableObject.BeginEdit() { __original = this.Clone(); }
            void System.ComponentModel.IEditableObject.CancelEdit() { UpdateWithAnother(this.__original); }
            void System.ComponentModel.IEditableObject.EndEdit() { }
          #>;
        }
      }
      root Agg {
        string x;
        Value v;
        has mixin EditableObject;
      }
      value Value {
        int i;
      }
    }

Now you can specify that mixin on every appropriate object.
But currently there are some downsides to this:
 * UpdateWithAnother is a method only available in client code
 * there is no way to specify c# only for client target

I guess I should add client as a target for implementation which would resolve your problem.
But try this out with latest compiler and let me know if that resolves your problem.

**Comment by Kobus-Smit** [comment]
Thanks @zapov I'm going to try it.

I'll have to remember to add it to each (probably most) objects, making the
DSL more verbose.

What are your reasons for not generating that as part of the client code?

**Comment by Kobus-Smit** [comment]
Yes the mentioned downsides makes it difficult to use in the case where you have one .sln with the client, common and server .csprojs:

![image](https://user-images.githubusercontent.com/11263864/45328010-3f391a80-b59d-11e8-8cca-c639cb79ef5b.png)

**Comment by zapov** [comment]
you can apply mixin on objects automatically by doing something like

    apply on all aggregates;

I'll look into adding additional target soon.

**Comment by Kobus-Smit** [comment]
Ok cool, I'm discovering/learning more about Revenj every time you respond. 
Thanks, much appreciated @zapov

**Comment by zapov** [comment]
I've released a new compiler. There is now a client target which you can use.

**Comment by Kobus-Smit** [comment]
Thanks @zapov 

Where in the dsl do I use that client target?

**Comment by Kobus-Smit** [comment]
Ah `implements client`

**Comment by Kobus-Smit** [comment]
Resolved, thanks again @zapov

**Comment by Kobus-Smit** [comment]
> Now you can specify that mixin on every appropriate object. But currently there are some downsides to this:
> 
> * UpdateWithAnother is a method only available in client code

Hi @zapov , hope you are well.

Would it be possible for the compiler to also generate the UpdateWithAnother method for POCOs?
We were using the Client library in our .NET framework project, and then after migrating to .NET Core we used the POCO DotNetStandard library. 

The only missing thing now is the UpdateWithAnother method does not exist when we use 

```
  implements c# 'System.ComponentModel.IEditableObject' { 
    <# 
    dynamic __original;
    void System.ComponentModel.IEditableObject.BeginEdit()  { __original = this.Clone(); }
    void System.ComponentModel.IEditableObject.CancelEdit() { UpdateWithAnother(this.__original); }
    void System.ComponentModel.IEditableObject.EndEdit()    { }
    #>; 
  } 
```

**Comment by zapov** [comment]
I would need to extend compiler to support something like that. And it would kind of conflict with this client and server version of change tracking.

If you can implement something to keep track of this objects and reset them back from clones that sounds much better than relying on the compiler support.

Eg, take snapshot via clone.
Replace objects in place via snapshots if cancel fails.

Its better if you architecture your app that way, than to rely on this POCO resets... as this makes them... not so much POCO.

**Comment by Kobus-Smit** [comment]
Yes. I hear you, but I cannot think how to implement it otherwise.
For the thirdparty UI components to correctly rollback, the objects must implement IEditableObject.

The mixin worked great with the C# client lib, but there is no C# client lib for .NET Core right?
So that is why I've just used the POCO lib.

**Comment by zapov** [comment]
I would be more interested in updating client lib to work with new .NET than adding this copy for POCO only.
Is this something which would resolve your issue?

**Comment by Kobus-Smit** [comment]
Yeah that would resolve the issue. 

We've used the client lib before but that was with the WCF service. We've replaced WCF with gRPC in .NET 5/6 using https://github.com/Cysharp/MagicOnion so we'll just depend on the POCO part and the UpdateWithAnother method.

**Comment by zapov** [comment]
I thought I released this last year :(
Will do it soon.

**Comment by Kobus-Smit** [comment]
Cheers, thanks mate

**Comment by zapov** [comment]
Its up: https://www.nuget.org/packages/Revenj.Client

**Comment by Kobus-Smit** [comment]
Thanks @zapov 

I'd probably have to use the cli to generate the client dll? I'll have a look next week.

Because the Client lib does not have a DotNetStandard build type as POCO and Postgres,
so there are errors.

![image](https://user-images.githubusercontent.com/11263864/188298486-e128e672-9bbf-4ec6-b010-8477d25718c4.png)


![image](https://user-images.githubusercontent.com/11263864/188298441-0a699865-3cf2-4023-b0a7-b5154cd2ccb0.png)

![image](https://user-images.githubusercontent.com/11263864/188298505-7bb23e1d-6ebc-40cd-b70a-82ec6493a347.png)

**Comment by zapov** [comment]
I released new VS plugin which adds this option to client.

**Comment by Kobus-Smit** [comment]
Thanks mate. 

I've used the new VS plugin and get [CS0656](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0656?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(CS0656)%26rd%3Dtrue) Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'


![image](https://user-images.githubusercontent.com/11263864/188299955-0cf0ca88-da93-4c2b-95ee-7a6d95897d60.png)


It compiles after adding the Microsoft.CSharp NuGet ([SO](https://stackoverflow.com/questions/40930080/asp-net-core-1-1-compiling-with-c-sharp-dynamic-missing-compiler-required-member))

Can you also gen this for the client project?
```
<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
```

**Comment by zapov** [comment]
You should be able to include this dependency in the deps at client page for Nuget
Just put it after revenj.client 0.9.0

**Comment by Kobus-Smit** [comment]
Ah of course :-)

![image](https://user-images.githubusercontent.com/11263864/188300548-ca3f88c8-f551-4809-bd3b-3c4fc5775c56.png)
