### ISSUE TITLE
UTC time

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#118]
Hi @zapov 

What does the `UTC time` checkboxes do?

![image](https://user-images.githubusercontent.com/11263864/46594585-cb4c4c80-cb1f-11e8-92f1-549563d08f62.png)

![image](https://user-images.githubusercontent.com/11263864/46595057-53cbec80-cb22-11e8-8ef2-6f30e8d2ea0a.png)

If the server always send UTC `DateTime`s, is there a way to always show the `DateTime`s in the client's local time?

**Comment by zapov** [comment]
dates are complicated ;)

Postgres doesn't really have native zone aware timestamp. That information gets lost once you save it to DB.
So when reading it you can read it into you local zone or UTC.
This option mostly specify how will you deal with such scenarios.
You should still be able to send local zoned dates around via JSON.

Since that is just a different representation of the same point in time, you should always configure your local timestamp display to use user defined settings (server default is good starting point, but often users have different zone than server)

**Comment by Kobus-Smit** [comment]
> dates are complicated ;)

Yep true. Nodatime does a better job than the .Net BCL and Npgsql v4.0+ can now use NodaTime https://www.npgsql.org/doc/types/nodatime.html

> Postgres doesn't really have native zone aware timestamp. That information gets lost once you save it to DB.

Yes that is unfortunate. Would have been nice if they had a Oracle `TIMESTAMP WITH TIME ZONE` or `DateTimeOffset` type as in SQL Server 2008+. https://blogs.msdn.microsoft.com/bartd/2009/03/31/the-death-of-datetime/

Possible workarounds, adding an extra timezone offset column or using a ISO 8601 text column. But that requires extra biolerplate code and have performance implications.

> So when reading it you can read it into you local zone or UTC.
> This option mostly specify how will you deal with such scenarios.

I've played around with those UTC checkbox combinations and it appears the .NET client always receive the same UTC DateTime (with Kind=Unspecified) from my server plugin (Server's timezone is UTC). I assumed unchecking the `UTC Time` checkbox in the generated client library would do a [ToLocalTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tolocaltime?view=netframework-4.7.2#System_DateTime_ToLocalTime)?

> You should still be able to send local zoned dates around via JSON.

Can you please elaborate?

>Since that is just a different representation of the same point in time, you should always >configure your local timestamp display to use user defined settings (server default is >good starting point, but often users have different zone than server)

Most of our users will have a different zone that the server. They can change their user defined timezone in the apps user prefs (It'll default to their Windows timezone)

How would you recommend a Revenj user handle the UTC dates from the server plugin?
Should we loop through the results and change the dates to the user's timezone preference? That would be a lot of boilerplate code?

Would it be technically possible to change Revenj to [ConvertTimeFromUtc](https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.converttimefromutc?view=netframework-4.7.2) the dates received over the wire to a specified TimeZoneInfo?

**Comment by zapov** [comment]
If I'm not mistaken regardless of that setting, if you send a UTC timestamp it will travel as UTC, if you send a local timestamp it will travel as local.

What I'm saying is that you control for presenting the value should format it accordingly. You should not be changing the values on your properties, but rather have some presentation conversion to appropriate format.

**Comment by Kobus-Smit** [comment]
I'm going to close this for now, will revisit later.
