### ISSUE TITLE
Internal compiler error

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#119]
I got this error Internal compiler error. Error compiling object model: Error running /usr/bin/mcs: Out of memory. Is there anything we can do to decrease the memory usage?
Thanks

**Comment by zapov** [comment]
On the latest compiler? Can you try on latest version?

I suspect it's something specific to your model.

**Comment by araneta** [comment]
where is the latest compiler?

**Comment by zapov** [comment]
The tools download it from here: https://tools.dsl-platform.com/dsl-compiler.zip

**Comment by zapov** [comment]
@araneta did the latest compiler resolved the issue?
A month ago there was also a significant change to the compiler which might also help

**Comment by araneta** [comment]
i got another error using mono 
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com


```
java -jar dsl-clc.jar properties=multi.props
Creating SQL migration for Postgres ...
Error creating SQL migration:
Could not load signature of h+e:al due to: Could not load file or assembly or one of its dependencies. assembly:System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Could not load signature of bxb:al due to: Could not load file or assembly or one of its dependencies. assembly:System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>

Unhandled Exception:
System.TypeLoadException: Could not load type 'h+e' from assembly 'dsl-compiler, Version=1.8.6489.26636, Culture=neutral, PublicKeyToken=null'.
  at h.a (System.String[] A_0) [0x00201] in <6b3e3843a65f44d19692b7cda9a7c1ff>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'h+e' from assembly 'dsl-compiler, Version=1.8.6489.26636, Culture=neutral, PublicKeyToken=null'.
  at h.a (System.String[] A_0) [0x00201] in <6b3e3843a65f44d19692b7cda9a7c1ff>:0 


```

**Comment by araneta** [comment]
i solved the issue by upgrading to the latest mono
