### ISSUE TITLE
Delete cascade

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#120]
Hi @zapov 

Is it possible to configure a `relationship` in the dsl to generate an `on delete cascade` fk constraint?

**Comment by zapov** [comment]
I have this on my short term TODO task.
Currently, only non-aggregates are delete cascaded

**Comment by zapov** [comment]
This should work now for basic use cases. Eg.

    relationship<X> x { cascade delete; }

**Comment by Kobus-Smit** [comment]
Thanks @zapov , going to test it today!

**Comment by Kobus-Smit** [comment]
Works for me thanks @zapov , I love deleting unnecessary code :)
