### ISSUE TITLE
Missing version number for Revenj.Core.dll on Nuget

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#121]
Hi @zapov 

Revenj.Core.dll from https://www.nuget.org/packages/revenj/1.5.0 does not have a version number and this cause a compile warning:

![image](https://user-images.githubusercontent.com/11263864/53210620-9c7be080-3692-11e9-86bf-d20be57daa3b.png)

![image](https://user-images.githubusercontent.com/11263864/53210640-a69ddf00-3692-11e9-9965-7fd935d8a567.png)

![image](https://user-images.githubusercontent.com/11263864/53210626-a0a7fe00-3692-11e9-9419-e8f31d5e9d4d.png)

```
7>  There was a conflict between "Revenj.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=dea4f62beafbd724" and "Revenj.Core, Version=1.5.0.0, Culture=neutral, PublicKeyToken=dea4f62beafbd724".
7>      "Revenj.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=dea4f62beafbd724" was chosen because it was primary and "Revenj.Core, Version=1.5.0.0, Culture=neutral, PublicKeyToken=dea4f62beafbd724" was not.
```

**Comment by Kobus-Smit** [comment]
No problem when using the `net40` dll.

Should I reference the `net40` or the `netstandard2.0` dll in my .NET 4.7.1 project?

**Comment by zapov** [comment]
Yeah, it seems I didn't fully set up the project correctly. Will fix and release soon a new version.

Versions should be same, so I assume `netstandard2.0` should be preferable

**Comment by zapov** [comment]
I've released a new version: https://www.nuget.org/packages/Revenj.AspNetCore/

**Comment by Kobus-Smit** [comment]
Resolved
