### ISSUE TITLE
NuGet for other Revenj binaries?

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#122]
Hi @zapov 

I'm now using https://www.nuget.org/packages/revenj/1.5.0 for Revenj Core.

The rest of the Revenj binaries we need to download from GitHub. 
Do you consider adding `Revenj.Processing.Interface.dll`, `Revenj.Wcf.dll`, `Revenj.Client` etc.  to NuGet as well?
That would be more consistent and easier to use and update.

**Comment by zapov** [comment]
Long time ago I actually tried to release http project on Nuget, but it did not like that it's an exe ;(

I did release `Revenj.AspNetCore` now which has the processing and the commands.

I'll look into releasing Client version too

**Comment by Kobus-Smit** [comment]
As mentioned in https://github.com/ngs-doo/revenj/issues/161#issuecomment-885453677 

> " Will look into publishing it hopefully under .net standard 2.0, but if there are some problems, probably for this 5.0 version
> It seems I never manage to get around actually finishing this work, but I'll plan to make a Revenj version which works alongside ASP.NET core + publish all projects on Nuget. I did plan on resolving this issues end of next month'

**Comment by Kobus-Smit** [comment]
Published https://www.nuget.org/packages/Revenj.Client
