### ISSUE TITLE
16 bit integer dsl data type

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#124]
Hi @zapov 

What is the dsl data type for a 16-bit integer C#  `short`  Postgres `smallint`?
I've a requirement to use `smallint` for a very large database.

**Comment by zapov** [comment]
I skipped it on purpose for some reasons of the time, but yeah it makes sense to have it.
I'll add it.

**Comment by Kobus-Smit** [comment]
Thank you!

**Comment by Kobus-Smit** [comment]
Hi @zapov , do you have an ETA for this one? 
Much appreciated.

**Comment by zapov** [comment]
It might be done today (but it will have dependencies on other libraries which will not be released yet)

**Comment by Kobus-Smit** [comment]
Thank you very much. Is it just a new dsl-compiler.exe? What do you mean with other unreleased libraries?

**Comment by zapov** [comment]
I mean revenj and dsl-json (for Java version)

**Comment by Kobus-Smit** [comment]
Ok

**Comment by Kobus-Smit** [comment]
Thank you @zapov !

Works fine with compiler 2.3.7002 and latest Revenj https://github.com/ngs-doo/revenj/commit/9f069173d62ad776540b30c6456ba771b7c88cb8
