### ISSUE TITLE
exclude schema from deletion

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#131]
in the beginning i have 2 modules, module test1 and module test2 in the dsl file. i want to delete this test1 from dsl file but i don't want to delete that schema on the db. is it possible to do this? so basically i want to target the dsl file to specific schema because it will take so much time if we have too many modules in dsl file.
Thanks

**Comment by zapov** [comment]
If you take a look at the generated SQL you can see that there are guards before dropping objects.
So if you don't want to drop some schema you can remove 'NGS generated' comment from that schema.
Not sure that will do what you want in the end.

**Comment by araneta** [comment]
ok thanks i will try it
