### ISSUE TITLE
Problem opening the solution in VS2013

### ISSUE THREAD

**Issue by hperadin** [ngs-doo/revenj#24]
Some projects contain a reference to:

    (...)\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets

Which prevents the loading and building of some projects when using a different version of Visual Studio. Manually changing the path to the locally installed version temporarily fixes the issue.

**Comment by zapov** [comment]
Fixed
