### ISSUE TITLE
Make JinqQueryProvider public

### ISSUE THREAD

**Issue by instant-hrvoje** [ngs-doo/revenj#42]
Change org.revenj.spring.JinqQueryProvider class visibility to public to support custom configuration scenarios for revenj.spring

**Comment by zapov** [comment]
Sure, we can change that... although I would be more eager to change RevenjStartup, understand why not use that instead.

**Comment by zapov** [comment]
I've added public static method so you can initialize it without faking package name: https://github.com/ngs-doo/revenj/blob/master/java/revenj-spring/src/main/java/org/revenj/spring/RevenjStartup.java#L64
