### ISSUE TITLE
SQL specification missing implements specification

### ISSUE THREAD

**Issue by AnaMarjanica** [ngs-doo/revenj#45]
Generated specification from SQL type doesn't implement Specification
```
  sql TransportUserVersion
  <# SELECT uri as username,at,snapshot FROM "trading"."-ngs_TransportUser_history-" ORDER BY at DESC #> {
    String username;
    Timestamp at;
    String snapshot;

    specification findUserVersions 'it => it.username == username && it.at <= timeRequested'
    {
      String username;
      Timestamp timeRequested;
    }
  }
```

Shouldn't this one:
public static class findUserVersions implements java.io.Serializable, com.dslplatform.json.JsonObject
be like this:
public static class findUserVersions implements java.io.Serializable, org.revenj.patterns.Specification&lt;TransportUserVersion&gt;?

**Comment by zapov** [comment]
Yeah it should probably. I'll add it eventually.
You can use lambda expression on Query as workaround for now.

**Comment by zapov** [comment]
Fixed.
