### ISSUE TITLE
Revenj.Java: Sum lambda does not compile

### ISSUE THREAD

**Issue by melezov** [ngs-doo/revenj#51]
aggregate Account {
        Vector<CashFlow> cashFlaw;
        calculated Decimal(2) insum from 'it => it.cashFlaw.Sum(cf => cf.inflow)';
    }
  
    value CashFlow {
        Decimal(2) inflow;
    }

Produres:

`Unable to convert calculated property: insum in bank.Account into Java lambda expression: Java operator not supported: Sum()`

**Comment by zapov** [comment]
Fixed.
