### ISSUE TITLE
Referencing a root in a Snowflake from relationship

### ISSUE THREAD

**Issue by rinmalavi** [ngs-doo/revenj#54]
root A { }
    
    root B {
      Int aid;
      Relationship a(aid) A;
    }

    snowflake<A> BView {
      a;
    }

Property a in object __.B is not defined. Possible alternative: aID

**Comment by zapov** [comment]
Yeah, "a" is not a property. Will look into what can be done about it.

**Comment by zapov** [comment]
Use an ordinary reference for such use cases.
Reference implies relationship, so this would just cause confusion without much benefit.
Now that you can create shallow references for easier persistence there is rarely a reason not to use it.
