### ISSUE TITLE
Error while converting an empty mixin implementation inside entity

### ISSUE THREAD

**Issue by melezov** [ngs-doo/revenj#57]
Insert is successul, select fails due to IOException when parsing empty ImplVoid tuple.

    module mixintest
    {
      aggregate Foo {
        List<Bar> bars;
      }
      
      entity Bar {
        String name;
        String description;
        Mixin  mixin;
      }
      
      mixin Mixin;
      
      value ImplVoid {
        has mixin Mixin;
      }
    }

**Comment by zapov** [comment]
Fixed.
