### ISSUE TITLE
use -source 8 or higher to enable lambda expressions)

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#67]
I got this error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project revenj-boot: Compilation failure: Compilation failure:
[ERROR] /home/aldo/IdeaProjects/revenjboot/target/generated-sources/hello/repositories/WorldRepository.java:[79,21] try-with-resources is not supported in -source 1.6
[ERROR] (use -source 7 or higher to enable try-with-resources)
[ERROR] /home/aldo/IdeaProjects/revenjboot/target/generated-sources/hello/repositories/WorldRepository.java:[93,91] lambda expressions are not supported in -source 1.6
[ERROR] (use -source 8 or higher to enable lambda expressions)
[ERROR] /home/aldo/IdeaProjects/revenjboot/target/generated-sources/hello/repositories/WorldRepository.java:[122,86] diamond operator is not supported in -source 1.6
[ERROR] (use -source 7 or higher to enable diamond operator)
[ERROR] /home/aldo/IdeaProjects/revenjboot/target/generated-sources/hello/repositories/WorldRepository.java:[123,56] multi-catch statement is not supported in -source 1.6
[ERROR] (use -source 7 or higher to enable multi-catch statement)
[ERROR] /home/aldo/IdeaProjects/revenjboot/target/generated-sources/hello/repositories/WorldRepository.java:[161,146] method references are not supported in -source 1.6
[ERROR] (use -source 8 or higher to enable method references)
[ERROR] /home/aldo/IdeaProjects/revenjboot/target/generated-sources/hello/converters/WorldConverter.java:[24,63] lambda expressions are not supported in -source 1.6
[ERROR] (use -source 8 or higher to enable lambda expressions)
[ERROR] /home/aldo/IdeaProjects/revenjboot/target/generated-sources/hello/converters/WorldConverter.java:[46,166] method references are not supported in -source 1.6
[ERROR] (use -source 8 or higher to enable method references)
[ERROR] /home/aldo/IdeaProjects/revenjboot/target/generated-sources/Boot.java:[52,123] diamond operator is not supported in -source 1.6
[ERROR] (use -source 7 or higher to enable diamond operator)
[ERROR] /home/aldo/IdeaProjects/revenjboot/target/generated-sources/Boot.java:[53,21] try-with-resources is not supported in -source 1.6
[ERROR] (use -source 7 or higher to enable try-with-resources)
[ERROR] /home/aldo/IdeaProjects/revenjboot/target/generated-sources/hello/World.java:[125,90] lambda expressions are not supported in -source 1.6
[ERROR] (use -source 8 or higher to enable lambda expressions)
[ERROR] /home/aldo/IdeaProjects/revenjboot/target/generated-sources/hello/World.java:[126,29] try-with-resources is not supported in -source 1.6
[ERROR] (use -source 7 or higher to enable try-with-resources)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

when running mvn install
how to fix this?

**Comment by zapov** [comment]
Try instructing Maven to use java 8 as baseline. You can see example of it here: https://github.com/ngs-doo/revenj/blob/master/java/revenj-core/pom.xml#L103

**Comment by zapov** [comment]
Oh, you got this on RevenjBoot project?
I have Maven 3.3.9 here... so it works out of the box. I'll add that to pom so it works on older Maven versions too. But for now just add this snipet to pom.xml

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

**Comment by araneta** [comment]
Thanks its working
