### ISSUE TITLE
Event

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#69]
can you give me example how to submit event to this system and handle the event?
Thanks

**Comment by zapov** [comment]
You mean code example to go along with this article: https://github.com/ngs-doo/revenj/blob/master/tutorials/revenj-tutorial-handling-events.md

Even while article about events is for .NET most of it applies to JVM: https://github.com/ngs-doo/revenj/blob/master/tutorials/revenj-tutorial-event-sourcing.md
Basically do a POST to /Domain.svc/submit/EVENT_MODULE.EVENT_NAME

You can fine example handler in the tests: https://github.com/ngs-doo/revenj/blob/457b00150cacf881d9298ab23e3ab3c91aace57f/java/test/src/test/java/org/revenj/TestRepository.java#L117

**Comment by araneta** [comment]
Thanks
