### ISSUE TITLE
Disable DSL Compile 

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#72]
is it possible to only compile the dsl only when we update the dsl file? right now it always compiling dsl and creating automigrate like this everytime i run the spring boot even though i did not update the dsl file 

[INFO] --- dsl-platform-maven-plugin:1.1.0:sql-migration (default) @ revenj-boot ---
[info] Creating SQL migration for Postgres ...
[info] Migration saved to /home/aldo/IdeaProjects/revenjboot/sql/postgres-sql-migration-1483433536783.sql
[info] Applying migration...
[info] Database migrated and script renamed to: applied-postgres-sql-migration-1483433536783.sql
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ revenj-boot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] Copying 11 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ revenj-boot ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 87 source files to /home/aldo/IdeaProjects/revenjboot/target/classes

**Comment by zapov** [comment]
The spring-boot example has Maven set-up in a way to create sql migration in the 

    <phase>generate-sources</phase>

you can change it to something else to run in a different time.

But I suggest you wait a little, since I planned on fixing this script generation (there is some encoding issue which causes script to be regenerated). It's on my TODO list and I'll fix it soon.

**Comment by araneta** [comment]
ok thanks i will be waiting for you
Thanks

**Comment by zapov** [comment]
If you update Maven plugin to 1.1.1 it should stop creating those "empty" sql files

**Comment by araneta** [comment]
right now its using version 3.3, is it ok to update it to 1.1.1 ?
<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

**Comment by zapov** [comment]
I  was referring to

    <groupId>com.dslplatform</groupId>
            <artifactId>dsl-platform-maven-plugin</artifactId>
            <version>1.1.0</version>

**Comment by zapov** [comment]
Btw. You will also have to update dsl-compiler.exe since it contains a related change

**Comment by araneta** [comment]
i have updated the dsl platform maven plugin and the dsl-compiler.exe but it still generate migration scripts 
[INFO] 
[INFO] --- dsl-platform-maven-plugin:1.1.1:generate-code (default) @ revenj-boot ---
[info] Copying generated files from /tmp/DSL-Platform/projects/REVENJ_SPRING to target/generated-sources
[info] Boot file exists. Creating META-INF resources in:/home/aldo/projects/tamarind/target/classes/META-INF/services/org.revenj.extensibility.SystemAspect
[INFO] 
[INFO] --- dsl-platform-maven-plugin:1.1.1:sql-migration (default) @ revenj-boot ---
[info] Creating SQL migration for Postgres ...
[info] Migration saved to /home/aldo/projects/tamarind/sql/postgres-sql-migration-1483580711880.sql
[info] Applying migration...
[info] Database migrated and script renamed to: applied-postgres-sql-migration-1483580711880.sql
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ revenj-boot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] Copying 11 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ revenj-boot ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 90 source files to /home/aldo/projects/tamarind/target/classes

**Comment by zapov** [comment]
I think it should be good now.
Tested it out on both Windows and Linux.
