### ISSUE TITLE
How to query a single row

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#73]
I want to search a user from security model by username, how can i do that? i cant find the tutorial on this page https://github.com/ngs-doo/revenj/blob/master/tutorials/revenj-tutorial-jinq-basics.md

**Comment by zapov** [comment]
If this is your primary key it's best to use find method.
Otherwise `Query` should match `Stream` API... so you can use `findAny` or `findFirst` method.

**Comment by araneta** [comment]
thanks. Is it possible to query like this: Select * from users where username like %someuser% order by create_date ? thanks

**Comment by zapov** [comment]
Sure. Write it as you would use Java Stream API. This should work:

    query(User.class).filter(it -> it.username.contains("someuser")).sortedBy(User::createDate).findAny()

Look into tests for various examples: https://github.com/ngs-doo/revenj/blob/master/java/test/src/test/java/org/revenj/TestQuery.java#L349

**Comment by araneta** [comment]
Thanks a lot
