### ISSUE TITLE
Unique field

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#74]
how to set the field to unique
for example
root User()	{
		string(256) email;
		string(256) name;
		//Revenj supports Postgres arrays and this will be mapped to varchar[] in the database
		Set<string> roles;
		binary password;
		bool isAllowed;
	}
i want to make the email unique but not as a primary key
Thanks

**Comment by zapov** [comment]
email { unique; }

or 

    email;
    unique(email);

I've added support for grammar exploration to VS plugin. Plan on porting it to IDEA soon. Hope it will help answering such questions.

**Comment by zapov** [comment]
Also, I suggest you explore the model for test. It has various features there: https://github.com/ngs-doo/revenj/blob/master/java/test/src/test/resources/model.dsl#L322

**Comment by araneta** [comment]
Thanks

**Comment by araneta** [comment]
is it possible to set unique for 2 column for example unique for column col1 and col2?

**Comment by zapov** [comment]
Sure.

    unique(a,b);

**Comment by araneta** [comment]
Thanks
