### ISSUE TITLE
change the name column

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#75]
is it possible to set the column from dsl file?
right now this dsl
root University{
  string(256) name  {unique;}
  security.User *ownerUser;
}
will generate this table:
CREATE TABLE university."University"
(
  "ID" integer NOT NULL DEFAULT nextval('university."University_ID_seq"'::regclass), -- NGS generated
  name character varying(256) NOT NULL, -- NGS generated
  "ownerUserID" integer NOT NULL, -- NGS generated
...
}

its hard to use column with double quote

**Comment by zapov** [comment]
Its currently not allowed. This keeps name same in all domains. Different name can be mapped in sql concept but that will only map to preexisting db stuff.

Most people get used to quoting.
