### ISSUE TITLE
where the list stored?

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#79]
I have this model:
root Curriculum{
		University *University;
		Program *Program;
		int year;
		string(256) code;
		string(256) desc;
		int totalCredits;
		int maxSemester;
		
		List<CourseType>* courseTypes;
		List<CourseOffered>* courses;
	}
where did courseTypes and courses stored in the database? i cant find this column in Curriculum table
Thanks

**Comment by zapov** [comment]
Look into definition of entity views. They contain joins to binding tables

**Comment by araneta** [comment]
sorry i a little bit confused, here is my model
root Curriculum{
		University *University;
		Program *Program;
		int year;
		string(256) code;
		string(256) desc;
		int totalCredits;
		int maxSemester;
		
		List<CurriculumCourseTypeDetail>* courseTypes;
		List<CurriculumCourseOfferedDetail>* courses;
	}
	root CurriculumCourseTypeDetail{
		CourseType *CourseType;
		int minCredits;
	}
	root CurriculumCourseOfferedDetail{
		CourseOffered *CourseOffered;
		int minCredits;
	}

i want to be able to add courseTypes and course to curriculum, is it ok to use List? i see there is Set, Detail and [] int the example but i dont know which one that correct

**Comment by zapov** [comment]
Array/List/Set both map to N:N table in the database.
Detail maps to 1:N link (which is what people used most of the time in relational modeling).

What I meant when I said to look up entity view is ...
In PgAdmin (or your Postgres GUI tool) navigate to views and open up Curriculum_entity view
This is created by DSL compiler and it will show you how those tables are connected.

btw. there is no need for string(256).. you can just write string for your description.
your model seems fine. pick the type which works the best in your code. they are all array in Postgres

**Comment by zapov** [comment]
btw2. if those CurriculumCourseTypeDetail and CurriculumCourseOfferedDetail are only used from within the Curriculum it's better to mark them as entities, so they are all changed in one go. Then it won't be N:N anymore but rather 1:N (if you drop the pointer and let it define auto primary key)

**Comment by araneta** [comment]
thanks i have updated my model like you suggested 
root Curriculum{
		University *University;
		Program *Program;
		int year;
		string code;
		string desc;
		int totalCredits;
		int maxSemester;
		
		List<CurriculumCourseTypeDetail> courseTypes;
		List<CurriculumCourseOfferedDetail> courses;
	}
	entity CurriculumCourseTypeDetail{
		CourseType *CourseType;
		int minCredits;
	}
	entity CurriculumCourseOfferedDetail{
		CourseOffered *CourseOffered;
		int minCredits;
	}

**Comment by araneta** [comment]
when i tried to select the view i see there is an array: "{"(2,2,22,1028,0)","(3,3,12,1028,1)","(4,4,2,1028,2)"}" in courseTypesDetail column,
how this array arranged ?  i want to get the entity CourseType from List<CurriculumCourseTypeDetail> courseTypes or courseTypesDetail column
Thanks

**Comment by zapov** [comment]
Thats a Postgres projection to string. You can write calculated to get only specific column if you need that. eg

    calculated int[] detailsId from "it => it.courses.Select(c => c.CourseOfferedID).ToArray()";

If you want to query by it make it a actual column by extending calculated property with persisted

**Comment by araneta** [comment]
ok thank you for the explanation
