### ISSUE TITLE
snowflake with sorting and paging

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#80]
Is it possible to create a snowflake with sorting and paging? please give me some examples
Thanks

**Comment by zapov** [comment]
You can define default snowflake sort order using order by, e.g: https://github.com/ngs-doo/revenj/blob/master/java/test/src/test/resources/model.dsl#L54
But I'm not sure what you mean by paging. Repositories have limit/offset params for paging: https://github.com/ngs-doo/revenj/blob/master/java/revenj-core/src/main/java/org/revenj/patterns/SearchableRepository.java#L13 or https://github.com/ngs-doo/revenj/blob/master/java/revenj-core/src/main/java/org/revenj/patterns/DataContext.java#L26

**Comment by araneta** [comment]
i want the order by is using parameter is it possible?

**Comment by zapov** [comment]
Query API can be used for custom sorting. https://github.com/ngs-doo/revenj/blob/master/java/test/src/test/java/org/revenj/TestQuery.java#L388
Cube also has it's own (simpler) sorting

**Comment by araneta** [comment]
i want to put sorting and paging inside specification filterSearch, because search usually have sort and paging. is it possible?
Thanks
snowflake CourseOfferedList from CourseOffered{
		ID;
		University.ID as UniversityID;
		Program.ID as ProgramID;
		code;
		name;
		credit;
		CourseType.ID as CourseTypeID;
		CourseType.name as CourseType;
				
		specification filterSearch 'it =>
			it.UniversityID == univId &&
			it.ProgramID == programId && (
				filter == null ||
				filter == "" ||
				it.code.ToLower().Contains(filter.ToLower()) ||
				it.name.ToLower().Contains(filter.ToLower()))' {
			int     univId;
			int programId;
			String? filter;
		}
	}

**Comment by zapov** [comment]
Specification is just a predicate. If you wish to have filter + sort + paging you will have to provide additional parameters alongside specification.
If you want such definition inside DSL then you can write report, eg: https://github.com/ngs-doo/revenj/blob/master/java/test/src/test/resources/model.dsl#L121
You can use params for limit/offset

**Comment by araneta** [comment]
ok i will try it. Thanks

**Comment by araneta** [comment]
snowflake CourseOfferedList from CourseOffered{
		ID;
		University.ID as UniversityID;
		Program.ID as ProgramID;
		code;
		name;
		credit;
		CourseType.ID as CourseTypeID;
		CourseType.name as CourseType;
		
		specification findByUniversity 'it => it.UniversityID == univId'
		{
			int univId;
		}
		specification findByProgram 'it => it.UniversityID == univId && it.ProgramID == programId'
		{
			int univId;
			int programId;
		}
		specification findByCourseType 'it => it.UniversityID == univId && it.CourseTypeID == courseTypeId'
		{
			int univId;
			int courseTypeId;
		}
		specification filterSearch 'it =>
			it.UniversityID == univId &&
			it.ProgramID == programId && (
				filter == null ||
				filter == "" ||
				it.code.ToLower().Contains(filter.ToLower()) ||
				it.name.ToLower().Contains(filter.ToLower()))' {
			int     univId;
			int programId;
			String? filter;
		}
		order by code asc;
	}

why this order by code asc; does not work

**Comment by zapov** [comment]
It works, but it's not in the view.

**Comment by araneta** [comment]
so i have to use report instead of snowflake to use sorting and paging?

**Comment by zapov** [comment]
no? you can use query api to get that also. see link above to query test

**Comment by araneta** [comment]
ok i will use query
