### ISSUE TITLE
reference to self

### ISSUE THREAD

**Issue by araneta** [ngs-doo/revenj#81]
how to reference to self entity? 
    aggregate CourseOffered{
                List<CoursePrerequisite> prerequisiteCourses;
    }
    entity CoursePrerequisite{			
		CourseOffered *CourseOffered;	
		int minValue;		
	}

right now it generates
CREATE TABLE university."CoursePrerequisite"
(
  "CourseOfferedID" integer NOT NULL, -- NGS generated
  "minValue" integer NOT NULL, -- NGS generated
  "Index" integer NOT NULL, -- NGS generated
)
I want to be able to add another reference to courseOffered in CoursePrerequisite. how to do that?
Thanks

**Comment by zapov** [comment]
You can name references however you want. eg

    CourseOffered *ref1;
    CourseOffered *ref2;

**Comment by zapov** [comment]
The problem with your model is that you would get the same table even id you didnt write
    CourseOffered *CourseOffered;

Thats actually a backreference from the list property. Youve just exposed it that way. Meaning.... use a different name instead

**Comment by araneta** [comment]
i see.. thanks
