### ISSUE TITLE
Check if aggregate object is New?

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#91]
Using the Client library objects, how do I know if an aggregate is "New"?

I see the Update() method uses the internal __locator field to determine if it is new:

```
public global::Module1.Aggr1 Update()
{
  if (__locator == null) throw new ArgumentException("Can't update new aggregate");
  ...
```

**Comment by zapov** [comment]
Well, yeah... that's kind of can of worms.
That check is last line of defense that you can actually do an update, but you can have new objects which have a locator (although it is kind of rare for client library).

There are several ways this could be concluded... eg empty URI, but they all have downsides :(

What is the use case why this would be useful?

**Comment by Kobus-Smit** [comment]
Closing it for now, I found other ways.
