### ISSUE TITLE
Left join in dsl

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#93]
Given the model:
```
module Test {
  
  aggregate Place {
    string Name { unique; }
  }  

  aggregate User {
    string Username { unique; }
  }

  aggregate UserFavouritePlace(UserID, PlaceID) {
    User *User;
    Place *Place;
  }
}
```
I'd like to return the all places, showing a specific user's favourites first:
```
select p."Name", f."UserID" is not null "IsFavourite"
from "Test"."Place" p
left join "Test"."UserFavouritePlace" f on f."PlaceID" = p."ID" and f."UserID" = 1001
order by 2 desc, 1
```

Is it possible to define the above in the dsl? Or should I write a service side LINQ join query?

**Comment by zapov** [comment]
For the modeling part it would be useful to put in a detail concept in the users to their favorite places, eg:

    detail<UserFavouritePlace.User> FavoritePlaces;

and than you could use that user info with a list of places to construct such a list.

While you could write sql or linq concepts in DSL a better way to go about it would be just to use s server side linq query.

**Comment by Kobus-Smit** [comment]
It is still unclear to me how I would get clientside, a list of ALL the
places, with an extra column that indicate if the place is a favourite of
the specified users. Ie, the exact result of the join query above?

Could you perhaps please modify the above DSL to achieve that?

**Comment by Kobus-Smit** [comment]
Typo, should be:
...favourite of the specified USER...

**Comment by Kobus-Smit** [comment]
Problem with a server side LINQ query is how do I share the result with the client side? Then it is a mapping problem again, https://github.com/ngs-doo/revenj/issues/89

**Comment by zapov** [comment]
Well, you wouldn't. But you would have all the info to create such a list (by having list of all the places and having info about that specific user and his favorite places)

**Comment by zapov** [comment]
You can define sql and linq data sources. Client side can query that and will have the appropriate data structures.
But I'm not sure I understand what you mean... If you do it manually and define a struct which maps to the result of that query... and than do the query on the server side to populate it... thats not the same structure as places? or you wish to send the whole places object and some extra information?

**Comment by Kobus-Smit** [comment]
Yes I need the List of whole Places (in the real life project Place has a
few other complex properties) but with extra information yes, in this case
an extra column that show if the Place is a favourite of the User.

If you compile above DSL and enter data for some places, users and
favourites and then run above SQL you would see what the result is that I
need at the client side.

Currently I fetch the list of places and a list of favourites for logged in
user but then I have to manually join those 2 lists on the client side. Was
hoping to get that result in 1 call from the server, already joined.

**Comment by zapov** [comment]
I see. So my preferred approach to such problems would be to send the whole object and an extra column (which is not part of the original object) - but I guess you don't like that to much (at least you did not when you could navigate away from it).

I will add improvements to the automatic mapping this month (did some related work).
But I suggest sending an composite object with a place property and isFavorite property which seems the best solution from maintenance perspective

**Comment by Kobus-Smit** [comment]
I'm ok with the extra column for now. Looking forward to the automatic mapping improvements.
