### ISSUE TITLE
Postgres error - functions in index expression must be marked IMMUTABLE

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#97]
The migration script for the dsl below fails to apply because of 
`ERROR: 42P17: functions in index expression must be marked IMMUTABLE`

Culprit statement is
`CREATE UNIQUE INDEX "uq_ngs_uri_XYZ" ON "Test"."XYZ" (CAST("Type" as TEXT));`
Manually changing it to this works:
`CREATE UNIQUE INDEX "uq_ngs_uri_XYZ" ON "Test"."XYZ" ("Type");`

```c#
module Test {

aggregate XYZ(Type) {
  EnumX Type;
}

snowflake<XYZ> XYZs {
  Type;
}

enum EnumX {
  E1;
  E2;
}  

}
```

Using the DDD plugin in Visual Studio 2017 v15.5.7
Compiler v1.9.6592.23874
PostgreSQL v10

**Comment by Kobus-Smit** [comment]
Not a showstopper in my project, that index is not necessary because it is the same as the primary key index.

**Comment by Kobus-Smit** [comment]
Resolved with Compiler v2.0.6627.22972
Great thanks @zapov !

**Comment by Kobus-Smit** [comment]
Latest compiler fixed the above test case but I get the error with my full .dsl file.
I'll have to investigate more.

![image](https://user-images.githubusercontent.com/11263864/36574081-0bcf84f6-1898-11e8-986a-a6a6f075ea07.png)

**Comment by Kobus-Smit** [comment]
Should be replicable with this dsl.

It works if the `snowflake` is commented out.

```
module Test {

root XYZ(UserID, A, Type) {
  User *User;
  string A;
  EnumX Type;
  ABC(A,Type) *ABC;
}

snowflake<XYZ> XYZs {
  User.Name;
  A;
  Type;
}

root ABC(A, Type) {
  string A;
  EnumX Type;
}

enum EnumX {
  E1;
  E2;
}  

root User(Name) {
  string Name;
}

}

```

**Comment by zapov** [comment]
You need to have UserID in your snowflake. Otherwise it will try to create that cast

**Comment by Kobus-Smit** [comment]
Ok
