### ISSUE TITLE
Changelog for compiler?

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#98]
The dsl-compiler.exe's version got bumped from v1.9 to v2.0 recently. 

Is there a changelog available?
Were there any interesting changes/fixes?

**Comment by zapov** [comment]
Not really outside of source code ;(

I bump the compiler version when there is a need for DB migration due to compiler changes.
Eg, some indexes are not created any more, so a script dropped the old indexes if they were created with previous compiler version.

**Comment by Kobus-Smit** [comment]
Ok got it.
